chat-format: "{RANK}<reset> {PLAYER}<bold>âž¤</bold><reset><gray>{MESSAGE}</gray>"
rank-animations:
  default:
    frames:
      - "\uE000"
      - "\uE001"
      - "\uE002"
      - "\uE003"
      - "\uE004"
      - "\uE005"
      - "\uE006"
      - "\uE007"
  creator:
    frames:
      - "\uE100"
      - "\uE101"
      - "\uE102"
      - "\uE103"
      - "\uE104"
      - "\uE105"
      - "\uE106"
      - "\uE107"
      - "\uE108"
  jumal:
  special:
  admin:
    frames:
      - "\uE200"
      - "\uE201"
      - "\uE202"
      - "\uE203"
      - "\uE204"
      - "\uE205"
      - "\uE206"
      - "\uE207"
      - "\uE208"